name = "EarthquakeDiffinitive"
uuid = "9fa83511-5388-4054-9589-4ce011e12b61"
authors = ["Robin Dymér <robin.dymer@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Diffinitive = "5a373a26-915f-4769-bcab-bf03835de17b"

[compat]
Diffinitive = "0.1.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
